package gorilla

import (
	"database/sql"
	"log/slog"
	"net/http"

	"github.com/gorilla/mux"
	authServ "github.com/sabrs0/bmstu-web/src/internal/business/services/auth"
	"github.com/sabrs0/bmstu-web/src/internal/controllers"
	"github.com/sabrs0/bmstu-web/src/internal/dataAccess/repositories/postgres"
	"github.com/sabrs0/bmstu-web/src/internal/http-server/handlers/auth"
	"github.com/sabrs0/bmstu-web/src/internal/http-server/handlers/foundations"
	"github.com/sabrs0/bmstu-web/src/internal/http-server/handlers/foundrisings"
	"github.com/sabrs0/bmstu-web/src/internal/http-server/handlers/transactions"
	"github.com/sabrs0/bmstu-web/src/internal/http-server/handlers/users"
	authMW "github.com/sabrs0/bmstu-web/src/internal/http-server/middleware/auth"
	loggerMW "github.com/sabrs0/bmstu-web/src/internal/http-server/middleware/logger"
	_ "github.com/swaggo/http-swagger/example/gorilla/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func SetRouter(conn *sql.DB, logger *slog.Logger) *mux.Router { //мб сюда передать контроллеры ?
	foundationController := controllers.NewFoundationController(
		postgres.NewFoundationRepository(conn),
		postgres.NewTransactionRepository(conn),
		postgres.NewFoundrisingRepository(conn),
	)
	foundrisingController := controllers.NewFoundrisingController(
		postgres.NewFoundrisingRepository(conn),
		postgres.NewFoundationRepository(conn),
	)
	transactionController := controllers.NewTransactionController(
		postgres.NewFoundationRepository(conn),
		postgres.NewFoundrisingRepository(conn),
		postgres.NewUserRepository(conn),
		postgres.NewTransactionRepository(conn),
	)
	userController := controllers.NewUserController(
		postgres.NewFoundationRepository(conn),
		postgres.NewFoundrisingRepository(conn),
		postgres.NewUserRepository(conn),
		postgres.NewTransactionRepository(conn),
	)
	authController := controllers.NewLoginController(
		postgres.NewFoundationRepository(conn),
		postgres.NewUserRepository(conn),
		authServ.NewJWTService(),
	)
	const baseApiRoute = "/api/v1"
	mainRouter := mux.NewRouter()
	mainRouter.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8081/swagger/doc.json"),
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	)).Methods(http.MethodGet)
	router := mainRouter.PathPrefix(baseApiRoute).Subrouter()

	router.Use(loggerMW.New(logger))
	router.Use(mux.CORSMethodMiddleware(router))
	router.Use(mux.CORSMethodMiddleware(router))

	//ADMIN AUTH
	adminAuthRouter := router.Name("Admin Auth").Subrouter()

	adminAuthRouter.HandleFunc("/users", users.GetAll(logger, userController)).Methods("GET")

	adminAuthRouter.HandleFunc("/transactions", transactions.GetAll(logger, transactionController)).Methods("GET")
	adminAuthRouter.HandleFunc("/transactions/{id}", transactions.GetByID(logger, transactionController)).Methods("GET")
	adminAuthRouter.HandleFunc("/transactions/{id}", transactions.Delete(logger, transactionController)).Methods("DELETE", "OPTIONS")

	adminAuthRouter.Use(mux.CORSMethodMiddleware(adminAuthRouter))
	adminAuthRouter.Use(authMW.New([]string{"Admin"}, authServ.NewJWTService()))

	//NONE AUTH
	unAuthRouter := router.Name("None Auth").Subrouter() //PathPrefix(baseApiRoute).Subrouter()
	unAuthRouter.HandleFunc("/login", auth.Login(logger, authController)).Methods("POST", "OPTIONS")
	unAuthRouter.HandleFunc("/foundations", foundations.GetAll(logger, foundationController)).Methods("GET")
	unAuthRouter.HandleFunc("/foundrisings", foundrisings.GetAll(logger, foundrisingController)).Methods("GET")
	unAuthRouter.HandleFunc("/foundations/{id}",
		foundations.GetByID(logger, foundationController)).Methods("GET")
	unAuthRouter.Use(mux.CORSMethodMiddleware(unAuthRouter))
	//FOUNDATION AUTH
	foundationAuthRouter := router.Name("Foundation auth").Subrouter()

	foundationAuthRouter.HandleFunc(
		"/foundations/{id}/donate", foundations.Donate(logger, foundationController)).Methods("POST", "OPTIONS")
	foundationAuthRouter.Use(mux.CORSMethodMiddleware(foundationAuthRouter))
	foundationAuthRouter.Use(authMW.New([]string{"Foundation"}, authServ.NewJWTService()))
	//FOUNDATION ADMIN AUTH
	foundationAdminAuthRouter := router.Name("Foundation & Admin Auth").Subrouter()

	foundationAdminAuthRouter.Use(mux.CORSMethodMiddleware(foundationAdminAuthRouter))
	foundationAdminAuthRouter.Use(authMW.New([]string{"Foundation", "Admin"}, authServ.NewJWTService()))

	foundationAdminAuthRouter.HandleFunc("/foundations", foundations.Add(logger, foundationController)).Methods("POST", "OPTIONS")
	foundationAdminAuthRouter.HandleFunc("/foundations/{id}",
		foundations.GetByID(logger, foundationController)).Methods("PUT", "OPTIONS")
	foundationAdminAuthRouter.HandleFunc("/foundations/{id}",
		foundations.Delete(logger, foundationController)).Methods("DELETE", "OPTIONS")
	foundationAdminAuthRouter.HandleFunc("/foundations/{id}/foundrisings",
		foundations.GetFoundrisings(logger, foundationController)).Methods("GET")

	foundationAdminAuthRouter.HandleFunc("/foundrisings",
		foundrisings.Add(logger, foundrisingController)).Methods("POST", "OPTIONS")
	foundationAdminAuthRouter.HandleFunc("/foundrisings/{id}",
		foundrisings.Update(logger, foundrisingController)).Methods("PUT", "OPTIONS")
	foundationAdminAuthRouter.HandleFunc("/foundrisings/{id}",
		foundrisings.UpdateOptional(logger, foundrisingController)).Methods("PATCH", "OPTIONS")
	foundationAdminAuthRouter.HandleFunc("/foundrisings/{id}",
		foundrisings.Delete(logger, foundrisingController)).Methods("DELETE", "OPTIONS")

	//FOUNDATION ADMIN USER AUTH
	foundationUserAdminAuthRouter := router.Name("Foundation & Admin & User Auth").Subrouter()
	foundationUserAdminAuthRouter.Use(authMW.New([]string{"Foundation", "Admin", "User"}, authServ.NewJWTService()))
	foundationUserAdminAuthRouter.HandleFunc("/foundrisings/{id}",
		foundrisings.GetByID(logger, foundrisingController)).Methods("GET")

	foundationUserAdminAuthRouter.Use(mux.CORSMethodMiddleware(foundationUserAdminAuthRouter))
	foundationUserAdminAuthRouter.Use(authMW.New([]string{"Admin", "Foundation", "User"}, authServ.NewJWTService()))

	//USER ADMIN AUTH
	userAdminAuthRouter := router.Name("User & Admin Auth").Subrouter()

	userAdminAuthRouter.HandleFunc("/users", users.Add(logger, userController)).Methods("POST", "OPTIONS")
	userAdminAuthRouter.HandleFunc("/users/{id}", users.Update(logger, userController)).Methods("PUT", "OPTIONS")
	userAdminAuthRouter.HandleFunc("/users/{id}", users.Delete(logger, userController)).Methods("DELETE", "OPTIONS")
	userAdminAuthRouter.HandleFunc("/users/{id}", users.GetByID(logger, userController)).Methods("GET")

	userAdminAuthRouter.Use(mux.CORSMethodMiddleware(userAdminAuthRouter))
	userAdminAuthRouter.Use(authMW.New([]string{"User", "Admin"}, authServ.NewJWTService()))
	//USER AUTH
	userAuthRouter := router.Name("User Auth").Subrouter()

	userAuthRouter.HandleFunc("/users/{id}/donate", users.Donate(logger, userController)).Methods("POST", "OPTIONS")

	userAuthRouter.Use(mux.CORSMethodMiddleware(userAuthRouter))
	userAuthRouter.Use(authMW.New([]string{"User"}, authServ.NewJWTService()))

	return mainRouter

}
